import { Lato } from "next/font/google";
import "./globals.css";
import LoadingProvider from "@/components/loaderprovider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-lato',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lato.variable}`}>
      <body>
      <LoadingProvider>
        {children}
      </LoadingProvider>
      </body>
    </html>
  );
}
