import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar.jsx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
  variable: '--font-lato',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${lato.variable}`}>
      <body>
      <Navbar />
        {children}
      </body>
    </html>
  );
}
